info:
  description: '{cipher}AQBT6lIW/EP4wEb7ngl1McayNg0dWgGnzGc/DLl4qcXdFtWV4SWtFoiA7HoU6hLsAheDbbU1j48NHK5+VBmQSgHY7ysANB+KBtaEiT9NJE4w/rmt8bH+9XvAbTWT1KFAp+3oOhoSdvYVjj1oWeDBkS9kuABvSWUB+nRICY5JXYCL3DiHH+FdCjD4fy68qdLYr9s+noH7HyTFjdsKmHocuQBKus+tESkD6vAkYOv0/TgKKC5Q1aH8DNIi0l1IS5lfsL7e66MyZakHa0RIugRKDtp39ksiUmah3NrM5oSvc5+ZyXFddBlESYfdMiFhyXeURv6LHXvv620y0p5ibzWP1NJg5+Ra7Oc1Rz4dQCNL7apUZikM2IXtnwmnPGwBjgpWrkMzAf3KckSyrkcLZn4l26Z/ju1HyLDfYe+a7sH5BIdQ8Q=='
  url: https://github.com/spring-cloud-samples
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
foo: baz

---
spring:
  profiles: cloud
  cloud:
    config:
      uri: ${vcap.services.${PREFIX:}configserver.credentials.uri:http://user:password@${PREFIX:}configserver.${application.domain:cfapps.io}}
oauth2:
  client:
    tokenUri: ${vcap.services.${PREFIX:}sso.credentials.tokenUri:}
    authorizationUri: ${vcap.services.${PREFIX:}sso.credentials.authorizationUri:}
    clientId: ${vcap.services.${PREFIX:}sso.credentials.clientId:}
    clientSecret: ${vcap.services.${PREFIX:}sso.credentials.clientSecret:}
  resource:
    tokenInfoUri: ${vcap.services.${OAUTH2_RESOURCE_SERVICEID:${oauth2.resource.serviceId:sso}}.credentials.tokenInfoUri:}
    serviceId: ${PREFIX:}resource
application:
  domain: ${APPLICATION_DOMAIN:cfapps.io}
endpoints:
  restart: enabled
eureka:
  password: password
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:${eureka.password:}@${PREFIX:}eureka.${application.domain:cfapps.io}}/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

---
spring:
  profiles: docker
  cloud:
    config:
      uri: http://${CONFIGSERVER_1_PORT_8888_TCP_ADDR:localhost}:8888
endpoints:
  restart: enabled
eureka:
  instance:
    nonSecurePort: 80
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_1_PORT_8761_TCP_ADDR:localhost}:8761/eureka/

